spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "catvnsmc@gmail.com"
    password: "jcfo wdta vyvh eqrn"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            debug: true
server:
  port: 8080
