spring:
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
    timeout: 1800
    servlet:
      session-timeout: 1800
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            debug: true
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        max-age: 1800